site_name: "Mathilde BOCQUET"
logo: images/IMG_2028.png
theme:
  name: material
  palette:
    # Mode clair
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre

    # Mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs           # Active la barre de menu en haut
    - navigation.tabs.sticky    # Garde le menu en haut même quand on descend
nav:
  - Accueil: index.md
  - Colles: 
      - MPSI: colles/mpsi.md
      - MP*: colles/mp.md
  - Motivation: motivation.md
  
  
  
